apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    env: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        env: homework
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

        volumeMounts:
          - name: nginx-index-volume
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
    volumes:
      - name: nginx-index-volume
        configMap:
          name: nginx-index-config